# Generated by Django 5.0.1 on 2026-01-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("hero_image_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("secondary_color", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("accreditation", models.CharField(blank=True, max_length=255)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("storage_bucket", models.CharField(blank=True, max_length=255)),
                ("storage_region", models.CharField(blank=True, max_length=100)),
                ("storage_folder", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_university_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "University Profile",
                "verbose_name_plural": "University Profiles",
                "db_table": "university_profile",
            },
        ),
    ]
