# Generated by Django 5.0.1 on 2026-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_club_clubmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="faculty_mentor_name",
            field=models.CharField(
                blank=True,
                help_text="Display name of faculty mentor for this club",
                max_length=255,
            ),
        ),
    ]
