# Generated by Django 5.0.1 on 2026-01-27 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_approvalrequest_approvalhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("cultural", "Cultural"),
                            ("technical", "Technical"),
                            ("sports", "Sports"),
                            ("social", "Social Service"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("competition", "Competition"),
                            ("fundraiser", "Fundraiser"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_joint_event", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("registration_start", models.DateTimeField(blank=True, null=True)),
                ("registration_end", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=255)),
                ("venue_address", models.TextField(blank=True)),
                ("is_online", models.BooleanField(default=False)),
                ("online_meeting_link", models.URLField(blank=True)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("current_registrations", models.IntegerField(default=0)),
                ("requires_registration", models.BooleanField(default=False)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_expense",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("budget_category", models.CharField(blank=True, max_length=100)),
                (
                    "sponsorship_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("members_only", "Members Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("poster_url", models.URLField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("gallery_urls", models.JSONField(blank=True, default=list)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("actual_participants", models.IntegerField(blank=True, null=True)),
                ("feedback_collected", models.BooleanField(default=False)),
                ("report_generated", models.BooleanField(default=False)),
                ("report_url", models.URLField(blank=True)),
                (
                    "success_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_detail",
                        to="authentication.approvalrequest",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collaborating_clubs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joint_events",
                        to="authentication.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to="authentication.club",
                    ),
                ),
                (
                    "primary_coordinator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Organizer"),
                            ("co_organizer", "Co-Organizer"),
                            ("sponsor", "Sponsor"),
                            ("partner", "Partner"),
                            ("supporter", "Supporter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "budget_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("resource_contribution", models.TextField(blank=True)),
                ("volunteer_count", models.IntegerField(default=0)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_collaborations",
                        to="authentication.club",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaboration_coordinator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="authentication.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Event Created"),
                            ("updated", "Event Updated"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Event Approved"),
                            ("rejected", "Event Rejected"),
                            ("started", "Event Started"),
                            ("completed", "Event Completed"),
                            ("cancelled", "Event Cancelled"),
                            ("closed", "Event Closed"),
                            ("budget_updated", "Budget Updated"),
                            ("collaborator_added", "Collaborator Added"),
                            ("collaborator_removed", "Collaborator Removed"),
                            ("participant_registered", "Participant Registered"),
                            ("report_generated", "Report Generated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_changed", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="authentication.event",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EventReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("summary", "Event Summary"),
                            ("financial", "Financial Report"),
                            ("feedback", "Feedback Report"),
                            ("attendance", "Attendance Report"),
                            ("comprehensive", "Comprehensive Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("total_participants", models.IntegerField(default=0)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "budget_variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("objectives_met", models.TextField(blank=True)),
                ("challenges_faced", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("feedback_count", models.IntegerField(default=0)),
                ("feedback_summary", models.TextField(blank=True)),
                ("photos_count", models.IntegerField(default=0)),
                ("videos_count", models.IntegerField(default=0)),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("report_file_url", models.URLField(blank=True)),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="authentication.event",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="authenticat_status_44a21f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["primary_club", "status"], name="authenticat_primary_e46d86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_joint_event"], name="authenticat_is_join_cb4ae1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["-created_at"], name="authenticat_created_9e6d61_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventcollaborator",
            unique_together={("event", "club")},
        ),
    ]
