# Generated by Django 5.0.1 on 2026-01-27 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_event_eventcollaborator_eventlog_eventreport_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("physical", "Physical"), ("digital", "Digital")],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("room", "Room/Hall"),
                            ("equipment", "Equipment"),
                            ("vehicle", "Vehicle"),
                            ("software", "Software License"),
                            ("hardware", "Hardware"),
                            ("lab", "Laboratory"),
                            ("sports", "Sports Facility"),
                            ("av_equipment", "Audio/Visual Equipment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="For rooms/halls - seating capacity",
                        null=True,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical specs, features, etc.",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("room_number", models.CharField(blank=True, max_length=50)),
                (
                    "access_url",
                    models.URLField(blank=True, help_text="URL for digital resources"),
                ),
                ("license_key", models.CharField(blank=True, max_length=500)),
                (
                    "concurrent_users",
                    models.IntegerField(
                        blank=True, help_text="Max simultaneous users", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_bookable", models.BooleanField(default=True)),
                (
                    "booking_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto Approval"),
                            ("manual", "Manual Approval"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "min_booking_duration",
                    models.DurationField(
                        blank=True, help_text="Minimum booking duration", null=True
                    ),
                ),
                (
                    "max_booking_duration",
                    models.DurationField(
                        blank=True, help_text="Maximum booking duration", null=True
                    ),
                ),
                (
                    "advance_booking_days",
                    models.IntegerField(
                        default=30, help_text="How many days in advance can be booked"
                    ),
                ),
                ("requires_faculty_approval", models.BooleanField(default=True)),
                ("requires_admin_approval", models.BooleanField(default=True)),
                (
                    "cost_per_hour",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "deposit_required",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, help_text="Manuals, guidelines, etc."
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResourceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                ("duration", models.DurationField()),
                ("purpose", models.TextField()),
                ("expected_attendees", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("faculty_approved", "Faculty Approved"),
                            ("admin_approved", "Admin Approved"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("faculty_approved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "deposit_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("setup_required", models.BooleanField(default=False)),
                ("setup_notes", models.TextField(blank=True)),
                ("special_requirements", models.TextField(blank=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("damage_report", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_approved_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_bookings",
                        to="authentication.club",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_bookings",
                        to="authentication.event",
                    ),
                ),
                (
                    "faculty_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_approved_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="authentication.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ResourceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_id", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Resource Created"),
                            ("updated", "Resource Updated"),
                            ("booking_created", "Booking Created"),
                            ("booking_approved", "Booking Approved"),
                            ("booking_rejected", "Booking Rejected"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("maintenance_started", "Maintenance Started"),
                            ("maintenance_completed", "Maintenance Completed"),
                            ("status_changed", "Status Changed"),
                            ("damage_reported", "Damage Reported"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("field_changed", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="authentication.resourcebooking",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="authentication.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Log",
                "verbose_name_plural": "Resource Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "status"],
                name="authenticat_resourc_b822b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category", "is_bookable"],
                name="authenticat_categor_7f6f2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcebooking",
            index=models.Index(
                fields=["resource", "start_time", "end_time"],
                name="authenticat_resourc_095ffc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcebooking",
            index=models.Index(
                fields=["status", "start_time"], name="authenticat_status_43aa61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcebooking",
            index=models.Index(
                fields=["booked_by", "-created_at"],
                name="authenticat_booked__18bbd7_idx",
            ),
        ),
    ]
