# Generated by Django 5.0.1 on 2026-01-28 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_resource_resourcebooking_resourcelog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="admin_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="admin_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_approved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="admin_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="budget_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_outcomes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculty_approved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_mentor_department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_mentor_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_mentor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="funding_source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="objectives",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="resource_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="risk_assessment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="safety_measures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="special_permissions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="target_audience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="volunteer_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_faculty_approval", "Pending Faculty Approval"),
                    ("faculty_rejected", "Faculty Rejected"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("admin_rejected", "Admin Rejected"),
                    ("approved", "Approved"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ClubApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("member_addition", "Member Addition"),
                            ("member_removal", "Member Removal"),
                            ("position_change", "Position Change"),
                            ("budget_request", "Budget Request"),
                            ("club_info_update", "Club Information Update"),
                            ("event_permission", "Event Permission"),
                            ("resource_request", "Resource Request"),
                            ("collaboration_request", "Collaboration Request"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason/justification for this request",
                    ),
                ),
                (
                    "application_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="\n        For member_addition: {target_user_id, target_username, target_email, proposed_position, reason}\n        For position_change: {user_id, current_position, new_position, effective_date, reason}\n        For budget_request: {amount, purpose, breakdown, expected_outcomes}\n        For resource_request: {resource_type, quantity, duration, purpose}\n        For club_info_update: {field_name, current_value, new_value}\n    ",
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("supporting_documents_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_faculty", "Pending Faculty Approval"),
                            ("faculty_approved", "Faculty Approved"),
                            ("faculty_rejected", "Faculty Rejected"),
                            ("pending_admin", "Pending Admin Approval"),
                            ("admin_approved", "Admin Approved"),
                            ("admin_rejected", "Admin Rejected"),
                            ("approved", "Approved"),
                            ("implemented", "Implemented"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_faculty",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                ("faculty_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("faculty_comments", models.TextField(blank=True)),
                ("faculty_rejection_reason", models.TextField(blank=True)),
                ("admin_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_comments", models.TextField(blank=True)),
                ("admin_rejection_reason", models.TextField(blank=True)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("implementation_notes", models.TextField(blank=True)),
                ("expected_impact", models.TextField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_reviewed_club_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="authentication.club",
                    ),
                ),
                (
                    "faculty_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty_reviewed_club_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_club_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_club_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Only visible to faculty/admin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="authentication.clubapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("absent", "Absent"),
                            ("present", "Present"),
                            ("partial", "Partial Attendance"),
                            ("excused", "Excused"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("verification_method", models.CharField(blank=True, max_length=50)),
                ("verification_data", models.JSONField(blank=True, default=dict)),
                ("session_number", models.IntegerField(default=1)),
                ("session_name", models.CharField(blank=True, max_length=100)),
                ("feedback_rating", models.IntegerField(blank=True, null=True)),
                ("feedback_text", models.TextField(blank=True)),
                ("feedback_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_eligible", models.BooleanField(default=False)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="authentication.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="EventCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_id", models.CharField(max_length=50, unique=True)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("participation", "Certificate of Participation"),
                            ("appreciation", "Certificate of Appreciation"),
                            ("winner", "Winner Certificate"),
                            ("runner_up", "Runner Up Certificate"),
                            ("completion", "Course Completion"),
                            ("achievement", "Achievement Certificate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("issued", "Issued"),
                            ("downloaded", "Downloaded"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("achievement_details", models.TextField(blank=True)),
                ("rank_position", models.IntegerField(blank=True, null=True)),
                ("template_name", models.CharField(default="default", max_length=100)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("certificate_url", models.URLField(blank=True)),
                ("verification_url", models.URLField(blank=True)),
                ("qr_code_url", models.URLField(blank=True)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "attendance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate",
                        to="authentication.eventattendance",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="authentication.event",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="EventExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_id", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("venue", "Venue Rental"),
                            ("equipment", "Equipment"),
                            ("catering", "Catering"),
                            ("decoration", "Decoration"),
                            ("printing", "Printing & Stationery"),
                            ("prizes", "Prizes & Awards"),
                            ("travel", "Travel & Transportation"),
                            ("marketing", "Marketing & Promotion"),
                            ("speakers", "Guest Speakers / Performers"),
                            ("miscellaneous", "Miscellaneous"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "gst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online", "Online Transfer"),
                            ("card", "Card Payment"),
                            ("upi", "UPI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("paid_to", models.CharField(max_length=255)),
                ("paid_to_contact", models.CharField(blank=True, max_length=100)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("bill_image_url", models.URLField(blank=True)),
                ("bill_pdf_url", models.URLField(blank=True)),
                ("ocr_processed", models.BooleanField(default=False)),
                ("ocr_data", models.JSONField(blank=True, default=dict)),
                (
                    "ocr_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ocr_processed_at", models.DateTimeField(blank=True, null=True)),
                ("ocr_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("reimbursed", "Reimbursed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="authentication.event",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("questions_answers", models.JSONField(blank=True, default=dict)),
                ("special_requirements", models.TextField(blank=True)),
                ("team_name", models.CharField(blank=True, max_length=100)),
                ("team_members", models.JSONField(blank=True, default=list)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="authentication.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="registration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance",
                to="authentication.eventregistration",
            ),
        ),
        migrations.AddIndex(
            model_name="clubapplication",
            index=models.Index(
                fields=["club", "status"], name="authenticat_club_id_605b0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clubapplication",
            index=models.Index(
                fields=["application_type", "status"],
                name="authenticat_applica_d7748c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubapplication",
            index=models.Index(
                fields=["submitted_by", "-created_at"],
                name="authenticat_submitt_5e19e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clubapplication",
            index=models.Index(
                fields=["status", "-created_at"], name="authenticat_status_776229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcertificate",
            index=models.Index(
                fields=["event", "status"], name="authenticat_event_i_266fb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcertificate",
            index=models.Index(
                fields=["user", "status"], name="authenticat_user_id_051bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcertificate",
            index=models.Index(
                fields=["verification_code"], name="authenticat_verific_a0dbf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcertificate",
            index=models.Index(
                fields=["-issued_at"], name="authenticat_issued__261d34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventcertificate",
            unique_together={("event", "user", "certificate_type")},
        ),
        migrations.AddIndex(
            model_name="eventexpense",
            index=models.Index(
                fields=["event", "status"], name="authenticat_event_i_1c1044_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventexpense",
            index=models.Index(
                fields=["status", "-created_at"], name="authenticat_status_0cd8c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventexpense",
            index=models.Index(
                fields=["submitted_by"], name="authenticat_submitt_bfdd8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="authenticat_event_i_b46c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["user", "status"], name="authenticat_user_id_c95aa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["-registered_at"], name="authenticat_registe_6c0b5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(
                fields=["event", "status"], name="authenticat_event_i_44cec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(
                fields=["user", "status"], name="authenticat_user_id_2dc036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventattendance",
            index=models.Index(
                fields=["certificate_eligible", "certificate_issued"],
                name="authenticat_certifi_45567f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventattendance",
            unique_together={("event", "user", "session_number")},
        ),
    ]
